Initial Layout for Rocket.Chat Flutter SDK #1
RocketChat/Rocket.Chat.Flutter.SDK pull request #2
Opened 2023-04-20 16:08 UTC by yatendra2001

## Description

This PR implements the layout and CI for Rocket.Chat Flutter SDK project as proposed in issue #1 . The project structure, CI/CD setup, and the dummy implementation of tests are included. The main packages created are `rocket_chat_embeddedchat_component` and `rocket_chat_api`.

**Packages:**

- `rocket_chat_embeddedchat_component`: Will contain the SDK with Flutter UI components for Rocket.Chat, allowing for easy embedding of the chat interface into other Flutter applications.
- `rocket_chat_api`: Provides the Dart-friendly API/stub for applications requiring in-depth modification of chat behaviour or using the chat engine as a messaging fabric.

Both packages include a sample app which will use the respective libraries to demonstrate the functionality and usage.

**CI/CD:**

- Added a GitHub Actions workflow for continuous integration, building, and testing.
- Included build scripts and tests for both packages and the sample app.
- The CI/CD will keep evolving as we move further.

**Tests:**

- Integrated dummy test directory for each package and their corresponding sample apps. This directory will contain unit_tests, integration_tests and widget_tests as we move along.

2023-04-20 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Flutter.SDK?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Flutter.SDK?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Flutter.SDK?pullRequest=2) it.</sub>

2023-04-23 08:55 UTC, Sing-Li requested changes
Please fix some of the minor `.gitignore` problems.  Thanks.

2023-04-23 08:55 UTC, Sing-Li commented on packages/rocket_chat_api/windows/flutter/generated_plugin_registrant.cc
> +//  Generated file. Do not edit.
@yatendra2001   please take a look at    https://github.com/flutter/flutter/blob/master/.gitignore

These generated files should not be committed.

2023-04-23 08:55 UTC, Sing-Li commented on packages/rocket_chat_embeddedchat_component/sample_app/linux/flutter/generated_plugin_registrant.cc
> +//  Generated file. Do not edit.
More files that should not be committed.

2023-04-23 08:55 UTC, Sing-Li commented on packages/rocket_chat_embeddedchat_component/sample_app/macos/Flutter/GeneratedPluginRegistrant.swift
> +//
More files to ignore.

2023-04-23 09:27 UTC, Sing-Li commented
Need also to make sure the workflows are legit by adding one of the monorepo management tools.   

Seems `Melos` ,  `mono_repo`,  `flutter_monorepo_build_tools` or other.

2023-04-24 03:51 UTC, yatendra2001 commented
@Sing-Li I've added new .gitignore rules and added Melos as a monorepo management tool.

2023-04-26 03:47 UTC, Sing-Li approved these changes
looks like good enough for the first commit.  Thx

2023-04-26 03:47 UTC, merged

2023-04-26 03:48 UTC, Sing-Li commented
closes #1